### ISSUE TITLE
Patch doesn't work

### ISSUE THREAD

**Issue by Icesythe7** [SnapperTT/lua-luajit-compound-operators#1]
Trying to patch 2.1.0 beta no errors but doesn't allow the use of the new operators just syntax error, also tried the fetch and apply script which also errors out just trying to download latest. Would love to use this, if you could just upload a static lib of latest with 5.2compat enabled or tell me what I'm doing wrong it would be appreciated!

**Comment by SnapperTT** [comment]
I've run the `fetch_and_apply_lua.sh`, it does work, but you have to be sure that you run `./lua` and not `lua` as that will run the installed one in your system.

The luajit fetch_and_apply is broken, I'm fixing it now

**Comment by SnapperTT** [comment]
I've fixed the luajit script and pushed the commit. Could you please verify that its working for you? Cheers!

**Comment by Icesythe7** [comment]
> I've fixed the luajit script and pushed the commit. Could you please verify that its working for you? Cheers!

Works like a charm now! I did notice you have to add ";" at the end or you get a syntax error but not a big deal (ie 
`local x = 0
x++
print(x)`
will syntax error but 
`local x = 0
x++;
print(x)`
works fine, if you could add bit wise operators and maybe -- it would be awesome and perfect! (maybe change lua comment to c style comment idk) thanks for the quick fix regardless!

**Comment by SnapperTT** [comment]
Cheers mate, I've updated the readme to include a note about ";".
